[project]
name = "git-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "w2many", email = "rustamgrankin2009@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
git-practice = "git_practice:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
